name: Build and Push Dev Docker Image

on:
  push:
    branches:
      - main   # Only build when main branch updates
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Dev Docker Image
        run: |
          IMAGE=ghcr.io/toomanyfiles/tmf-timetable-frontend
          echo "Building dev image from main branch"
          docker build -t ${IMAGE}:dev .
          echo "Pushing dev image..."
          docker push ${IMAGE}:dev
